swagger: "2.0"
info:
  title: "Peregrinus Model"
  version: "1.0.0"
  description: "The peregrinus model."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
parameters:
paths:
definitions:
